### ISSUE TITLE
segfault qhash.h: Directory not empty.

### ISSUE THREAD

**Issue by MightyPork** [marcogrecopriolo/guglielmo#10]
Sometimes I get crashes when using the DAB multiplex dropdown.

I caught it with gdb (release build), but it froze my desktop so I couldn't inspect it further (had to `kill` gdb from another TTY).

![IMG20220225161205](https://user-images.githubusercontent.com/2041118/155740387-eb7db2f7-ea80-4fa3-8d3c-d423256465cc.jpg)

This apparently does not happen in Debug build. Could be a race condition.

**Comment by marcogrecopriolo** [comment]
Sorry, I am not sure why but github is not notifying me of new defects or anything.
I have never seen segv's with my builds, but that very much looks like an internal QT issue.
I'll see if I can find anything.
What build are you running?

**Comment by MightyPork** [comment]
It's built from master, 1b563049c17d24399378ede75c73018367b83b62 and running on Arch Linux

> This apparently does not happen in Debug build

I was wrong, since I posted this I got the crash also with the Debug build

**Comment by marcogrecopriolo** [comment]
OK, could you tell me your QT version?

**Comment by MightyPork** [comment]
The package has version `5.15.3+kde+r133-1`
