### ISSUE TITLE
Packaging for Arch User Repository

### ISSUE THREAD

**Issue by Z3hka** [marcogrecopriolo/guglielmo#12]
Hey,
thank you for your great software.
I've created an Archlinux Package Build and submitted it to Arch User Repository[0] so Arch Linux users can install your software with less hassle.
I hope that is ok for you, ofc i link to your source repo have included the (hopefully) appropriate license info. If not please let me know.
In regards to that i have a few questions:
- As i only have an RTL-SDR to test i don't exactly know which libraries you require for other SDRs and what dependencies they have.
-  Do you have any preferences on the menu entry (.desktop file) that I'll create? Should i use the image in the README as the icon?
Thanks in advance for your support

[0] https://aur.archlinux.org/packages/guglielmo

**Comment by marcogrecopriolo** [comment]
Thank you so much, much appreciated!
Re icons either that in the readme, or https://github.com/marcogrecopriolo/guglielmo/blob/master/icons/guglielmo.ico.
Re devices libraries, I'll check and let you know.
