### ISSUE TITLE
Compilation error on Ubuntu 22.04

### ISSUE THREAD

**Issue by frspin** [marcogrecopriolo/guglielmo#13]
Compiling on Ubuntu 22.04 give an error:
`[ 28%] Building CXX object CMakeFiles/guglielmo.dir/src/dialogs.cpp.o
/mnt/Prog/ham/guglielmo/src/dialogs.cpp: In member function ‘void RadioInterface::handleSettingsAction()’:
/mnt/Prog/ham/guglielmo/src/dialogs.cpp:120:44: error: ‘class Ui::settings’ has no member named ‘remoteComboBox’; did you mean ‘modeComboBox’?
  120 |         settingsDialog->connect(settingsUi.remoteComboBox, SIGNAL(activated(const QString &)),
      |                                            ^~~~~~~~~~~~~~
      |                                            modeComboBox
/mnt/Prog/ham/guglielmo/src/dialogs.cpp:123:24: error: ‘class Ui::settings’ has no member named ‘remoteComboBox’; did you mean ‘modeComboBox’?
  123 |             settingsUi.remoteComboBox->setCurrentIndex(0);
      |                        ^~~~~~~~~~~~~~
      |                        modeComboBox
/mnt/Prog/ham/guglielmo/src/dialogs.cpp:125:24: error: ‘class Ui::settings’ has no member named ‘remoteComboBox’; did you mean ‘modeComboBox’?
  125 |             settingsUi.remoteComboBox->setCurrentIndex(1);
      |                        ^~~~~~~~~~~~~~
      |                        modeComboBox
make[2]: *** [CMakeFiles/guglielmo.dir/build.make:1367: CMakeFiles/guglielmo.dir/src/dialogs.cpp.o] Errore 1
make[1]: *** [CMakeFiles/Makefile2:85: CMakeFiles/guglielmo.dir/all] Errore 2
make: *** [Makefile:136: all] Errore 2

Regards

Franco Spinelli`

**Comment by marcogrecopriolo** [comment]
Builds on a clean clone in opensuse and ubuntu.
My best guess is that you have an old instance of ui_settings.h, from prior to the mpris changes.
Make clean should sort it.

**Comment by frspin** [comment]
Il 30/10/22 09:25, Marco Greco ha scritto:
> Builds on a clean clone in opensuse and ubuntu.
> My best guess is that you have an old instance of ui_settings.h, from 
> prior to the mpris changes.
> Make clean should sort it.

Make clean don't solve the problem.
Removing build folder and recreating it also.

A fresh clone of GIT repository solve the problem.

Regards

Franco Spinelli
