### ISSUE TITLE
Shared Library target

### ISSUE THREAD

**Issue by jwinarske** [marcogrecopriolo/guglielmo#15]
@marcogrecopriolo Hi there.  Thanks for the cool project!  I'm interested in adding a library target, factoring out the UI, and adding gRPC/Cap'nProto server (s).  Decoupling the QT code from the backend.  The goal is to use it in automotive grade Linux (AGL).

**Comment by marcogrecopriolo** [comment]
Noble cause, it will take a little while.
In fact you may be better off starting off from welle.io (although you do lose FM).
Both come from Qt-dab (and sdr-j-fm in guglielmo's case), and the work that we have been both doing is exactly to isolate the back end from the interface.
Me, sadly, I am also stuck with a daytime job, a sql scripting language, and a major restoration project, so I only throw half an hour of coding here and there, when I find one free.
I still haven't finished ditching code that is no longer used, to give you an idea of when I'm at...

**Comment by jwinarske** [comment]
That is helpful info. Thank you.

I do like the fact you have FM in there.  It's a good combo for AGL target markets.  I would consider adding NRSC5 as a module (only it's GPL-v3).

When I have something I'll share it out, and see if it makes sense to put the work into merging it.

Cheers

**Comment by marcogrecopriolo** [comment]
Sorry, I should have clarified - I have only pointed you in the direction of Welle.io because they have done much more UI factoring out than I have

**Comment by jwinarske** [comment]
No worries.  Makes sense.  Thanks!

**Comment by marcogrecopriolo** [comment]
I plan to be in the same same state as https://github.com/marcogrecopriolo/sqsl where the language parser and the runner as wholly self contained and packaged as a library, and several UIs use it directly.
It will just take me time.
