### ISSUE TITLE
Build and running

### ISSUE THREAD

**Issue by VinceBezzina** [marcogrecopriolo/guglielmo#17]
How do you install on a mac?
What OS are recommended to run it ?
Can you run it from from GNURadio?

**Comment by marcogrecopriolo** [comment]
If you want to just install on mac, download the installer and run it.
If you want to build it, either clone the repository, or download the source, install xcode, qt, and all of the required libraries, and follow the readme (it boils down to either qmake + make, or cmake + make).
I don't have a recommended OS.
No, it is a completely independent product from GNUradio.
