### ISSUE TITLE
after (make) done in ubuntu  , how to run the software ? 

### ISSUE THREAD

**Issue by khanfar** [marcogrecopriolo/guglielmo#2]
hi , i follow instruction and install it on ubuntu  , how to run the software ?
thanks

**Comment by khanfar** [comment]
i do ./appimage.sh
chmod u+x guglielmo-x86_64.AppImage
chmod u+x linuxdeployqt-continuous-x86_64.AppImage

then try double click in mouse on two app image and nothing happen .
is that correct method ???
please help

**Comment by khanfar** [comment]
i try this too :  

 sudo ./guglielmo-x86_64.AppImage
[sudo] password for a : 
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Audio: Sorry, format cannot be handledSegmentation fault

and this :  

@ubuntu:~/guglielmo$ ./guglielmo-x86_64.AppImage
Audio: Sorry, format cannot be handledSegmentation fault (core dumped)

**Comment by nmaster2042** [comment]
Here, after build, staying in the build dir I do:

$ ./guglielmo

And it's starting fine

**Comment by marcogrecopriolo** [comment]
git clone https://github.com/marcogrecopriolo/guglielmo
cd guglielmo
mkdir build
cd build
cmake .. -DRTLSDR=ON
make

after that, in the build directory there's a binary called guglielmo.
Just run it.

If you want to run the appImage, just download it from [here](https://github.com/marcogrecopriolo/guglielmo/releases/download/v0.1/guglielmo-x86_64-v0.1.AppImage) and just run it.
It seems to me like you still have build issues.

**Comment by khanfar** [comment]
i try it , look what i got : 
./guglielmo
Audio: Sorry, format cannot be handledSegmentation fault (core dumped)

**Comment by khanfar** [comment]
> git clone https://github.com/marcogrecopriolo/guglielmo
> cd guglielmo
> mkdir build
> cd build
> cmake .. -DRTLSDR=ON
> make
> 
> after that, in the build directory there's a binary called guglielmo.
> Just run it.
> 
> If you want to run the appImage, just download it from [here](https://github.com/marcogrecopriolo/guglielmo/releases/download/v0.1/guglielmo-x86_64-v0.1.AppImage) and just run it.
> It seems to me like you still have build issues.

i try it , look what i got :
./guglielmo
Audio: Sorry, format cannot be handledSegmentation fault (core dumped)

**Comment by khanfar** [comment]
> Here, after build, staying in the build dir I do:
> 
> $ ./guglielmo
> 
> And it's starting fine

i try it , look what i got :
./guglielmo
Audio: Sorry, format cannot be handledSegmentation fault (core dumped)

**Comment by marcogrecopriolo** [comment]
OK, so the issue is that your sound card doesn't support 48k sound, and the original Qt-dab Qt-audio output can cope with it.
I have put a fix which should avoid the panic.

do a

git pull
cd build
make

when you run it, go to settings and switch to portaudio sound.

**Comment by khanfar** [comment]
i do these command up gitpull and make and try and the software is open then when i start it it forced close and when i try to change from pl to portaudio it close too

./guglielmo
Audio: Sorry, format cannot be handled
we could not load libmirsdrapi-rsp
If that is not the device you were expecting, do not worry
OK, functions seem to be loaded
Found Rafael Micro R820T tuner
[R82XX] PLL not locked!
samplerate set to 2048000
Supported gain values (29): 49.6 48.0 44.5 43.9 43.4 42.1 40.2 38.6 37.2 36.4 33.8 32.8 29.7 28.0 25.4 22.9 20.7 19.7 16.6 15.7 14.4 12.5 8.7 7.7 3.7 2.7 1.4 0.9 0.0 
failed to open libairspy.so
Error = libairspy.so: cannot open shared object file: No such file or directory
failed to open libLimeSuite.so
OK, functions seem to be loaded
Problem with hackrf_open:HackRF not found 
gain will be set 50 to 254
Segmentation fault (core dumped)
@ubuntu:~/guglielmo/build$

**Comment by khanfar** [comment]
im do all these staff on ubuntu , after sucsess hope so , i hope to it can implement in rasperry pi3 , and make a portable radio auto start software when boot , hope you make next update easy and support rasbian pi

**Comment by marcogrecopriolo** [comment]
k
run

gdb ./guglielmo
run

and give me the stack when it crashes.
There is something wrong about your hardware.

**Comment by khanfar** [comment]
gdb ./guglielmo
GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./guglielmo...(no debugging symbols found)...done.
(gdb) run
Starting program: /home/mwk/guglielmo/build/guglielmo 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe794b700 (LWP 2362)]
[New Thread 0x7fffdd5f6700 (LWP 2363)]
[New Thread 0x7fffdcdf5700 (LWP 2364)]
[New Thread 0x7fffd75a9700 (LWP 2365)]
Audio: Sorry, format cannot be handled
we could not load libmirsdrapi-rsp
If that is not the device you were expecting, do not worry
OK, functions seem to be loaded
[New Thread 0x7fffcbfff700 (LWP 2367)]
[Thread 0x7fffcbfff700 (LWP 2367) exited]
[New Thread 0x7fffcbfff700 (LWP 2368)]
Found Rafael Micro R820T tuner
[R82XX] PLL not locked!
samplerate set to 2048000
Supported gain values (29): 49.6 48.0 44.5 43.9 43.4 42.1 40.2 38.6 37.2 36.4 33.8 32.8 29.7 28.0 25.4 22.9 20.7 19.7 16.6 15.7 14.4 12.5 8.7 7.7 3.7 2.7 1.4 0.9 0.0 
failed to open libairspy.so
Error = libairspy.so: cannot open shared object file: No such file or directory
failed to open libLimeSuite.so
OK, functions seem to be loaded
Problem with hackrf_open:HackRF not found 
gain will be set 50 to 254
[New Thread 0x7fffcb7fe700 (LWP 2369)]
[New Thread 0x7fffc4c86700 (LWP 2370)]

Thread 1 "guglielmo" received signal SIGSEGV, Segmentation fault.
0x00007ffff62c7a30 in QAudioOutput::start(QIODevice*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Multimedia.so.5
(gdb) 
(gdb)

**Comment by marcogrecopriolo** [comment]
clone and rebuild, I fixed it ages ago.
the point still remains that your audio card seems not to support 48000/float, so even if you get past this, you won't get any sound, at least with Qt audio.

**Comment by khanfar** [comment]
thanks i will delete it and install it again . i will tell you if something wrong

**Comment by khanfar** [comment]
this what i got when try cmake :
cmake .. -DRTLSDR=ON
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build type not specified: defaulting to release.
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- QWT Version: 6.1.3
-- Found Qwt: /usr/lib/libqwt-qt5.so  
CMake Warning (dev) at /snap/cmake/870/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (PkgConfig)
  does not match the name of the calling package (FFTW3f).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /snap/cmake/870/share/cmake-3.20/Modules/FindPkgConfig.cmake:70 (find_package_handle_standard_args)
  cmake/Modules/FindFFTW3f.cmake:6 (INCLUDE)
  CMakeLists.txt:106 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Checking for module 'fftw3f >= 3.0'
--   Found fftw3f , version 3.3.7
CMake Warning (dev) at /snap/cmake/870/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (FFTW3F)
  does not match the name of the calling package (FFTW3f).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/Modules/FindFFTW3f.cmake:40 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:106 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found FFTW3F: /usr/lib/x86_64-linux-gnu/libfftw3f.so  
-- Found zlib: 
-- Found LibSndFile: /usr/lib/x86_64-linux-gnu/libsndfile.so
-- Found LibSampleRate: /usr/lib/x86_64-linux-gnu/libsndfile.so
CMake Warning (dev) at /snap/cmake/870/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (PkgConfig)
  does not match the name of the calling package (Portaudio).  This can lead
  to problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /snap/cmake/870/share/cmake-3.20/Modules/FindPkgConfig.cmake:70 (find_package_handle_standard_args)
  cmake/Modules/FindPortaudio.cmake:8 (include)
  CMakeLists.txt:605 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Checking for module 'portaudio-2.0'
--   Found portaudio-2.0, version 19
-- Performing Test PORTAUDIO2_FOUND
-- Performing Test PORTAUDIO2_FOUND - Success
CMake Warning (dev) at /snap/cmake/870/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (PORTAUDIO)
  does not match the name of the calling package (Portaudio).  This can lead
  to problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/Modules/FindPortaudio.cmake:46 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:605 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found PORTAUDIO: /usr/include  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mwk/guglielmo/build
@ubuntu:~/guglielmo/build$

**Comment by khanfar** [comment]
is there chance to work on raspberry pi 3 ?

**Comment by khanfar** [comment]
to run it in raspberry pi 3 with touch screen on it , is there chance to run on pi ?

**Comment by khanfar** [comment]
how to create app image ?

**Comment by marcogrecopriolo** [comment]
there's a script called appImage.sh. run it.
It should work on a rPi 3 - but I haven't tried it.
In cmakelist.txt, comment line 88 (search for RPI)

**Comment by khanfar** [comment]
i see this in line 88 in cmakelist.txt :  

add_definitions (-DPRESET_NAME)
add_definitions (-D__THREADED_BACKEND)	# uncomment for use for an RPI
add_definitions (-D__MSC_THREAD__)

so uncomment what ?

**Comment by alexmyczko** [comment]
i guess it's time for a debian package... i was looking for welle.io to add FM support. but now there's your project. thank you
