### ISSUE TITLE
SDRPlay API V3.07 support ?

### ISSUE THREAD

**Issue by nmaster2042** [marcogrecopriolo/guglielmo#3]
It looks like support for RSP devices is using v 2.13 API.
Is a v 3.07 API support planned ?

**Comment by marcogrecopriolo** [comment]
To be fair - I only have a dabstick, so I can't test any other device.
I'll probably get round to doing a V3 RSP, but for now my priority is to add features...

**Comment by nmaster2042** [comment]
It's ok.
I have RSP2, Duo and Dx, so if you add this, I'll be happy to make tests.

**Comment by AsciiWolf** [comment]
Any update regarding this? I can also help testing (with my RSPdx on Fedora 35).

**Comment by marcogrecopriolo** [comment]
;-) The amount of time I have for my personal projects is quite limited.
I am currently working on an SQSL qt client. I'll see if I can tackle this some time in January.

**Comment by marcogrecopriolo** [comment]
Hey, I have just merged an SDR Play V3 device.
Wholly untested, beyond it builds, and it doesn't hang / crash if the device is missing.
Anyone willing to give it a try?

**Comment by marcogrecopriolo** [comment]
@nmaster2042 @AsciiWolf could you give it a try?

**Comment by nmaster2042** [comment]
@marcogrecopriolo: yes I'll build and test end of the week, Thanks to work
on this.

Le mer. 23 févr. 2022 à 09:30, Marco Greco ***@***.***> a
écrit :

**Comment by AsciiWolf** [comment]
I was sadly not able to build AppImage on my Fedora 35 system because of: `ERROR: The host system is too new.`

I have also tried a non-AppImage build, but it crashes on SIGSEGV (SEGV_ACCERR).

I sadly don't have more time at the moment to further debug this, sorry.

**Comment by nmaster2042** [comment]
I was able to build from source, it starts and detects RSP2pro with API
v3.07.

Sometimes I have to restart api_service.

I don't have DAB here so I only tried FM, seems to get something on
frequencies but sound is very bad, can't listen.

I don't know if it's a sdr issue or audio on my system.

I use my RSP2pro with other SDR software without any issues.

My OS is kubuntu 21.10.


Le dim. 27 févr. 2022 à 23:00, AsciiWolf ***@***.***> a
écrit :

**Comment by marcogrecopriolo** [comment]
@nmaster2042 I got a RSP1a on loan from Sdrplay - I got to the point of getting sound out of DAB, but not FM, which is weird because with V2 libs, everything works.
Bear with me.

**Comment by marcogrecopriolo** [comment]
@nmaster2042 @AsciiWolf sdrplay v3 is now supported if you pull the latest master.
If you are happy, could you close?

**Comment by nmaster2042** [comment]
@marcogrecopriolo: Just tried last commit, FM works well now with RSP2pro + API 3.07 ;-)
