### ISSUE TITLE
build for specific devices

### ISSUE THREAD

**Issue by catalinalb** [marcogrecopriolo/guglielmo#4]
Hello,

for the ones that aren´t so fit with linux commans, can you please add how to complie for RTL-SDR, sdrplay, hackrf etc? 

I would like to use it with the rtl-sdr so these -DXXX=ON commands ... dunno with what I should replace that XXX, YYY, ZZZ letters. 

Thank you

**Comment by marcogrecopriolo** [comment]
You don't need to build anything - just use the binary drop, it has been built with support for all available devices.
This said - currently the build process is the same as for qt-dab, and the devices are a subset of those supported by qt-dab with the same mnemonics.
From CMakeList.txt:

if(DEFINED AIRSPY)
	set(AIRSPY true)
	set(deviceChosen true)
endif ()

if(DEFINED SDRPLAY)
	set(SDRPLAY true)
	set(deviceChosen true)
endif ()

if(DEFINED RTLSDR)
	set(RTLSDR true)
	set(deviceChosen true)
endif ()

if(DEFINED HACKRF)
	set(HACKRF true)
	set(deviceChosen true)
endif ()

if(DEFINED LIMESDR)
	set(LIMESDR true)
	set(deviceChosen true)
endif ()

# choose all devices if none specified
if (NOT deviceChosen)
	set(AIRSPY true)
	set(SDRPLAY true)
	set(RTLSDR true)
	set(HACKRF true)
	set(LIMESDR true)
endif()

**Comment by catalinalb** [comment]
Thank you, I will try it for sure :)
