### ISSUE TITLE
Not an issue but build comments

### ISSUE THREAD

**Issue by miken101** [marcogrecopriolo/guglielmo#5]
Running on Linux Mint (based on Ubuntu 18.04) with Cinnamon desktop.

Appimage will not display graphics. (Possible known issue with QT and Cinnamon)
Had issues building with qmake due to my QT issues with multimedia.
Built successfully using cmake (had to update cmake from distribution release)

Running in DAB mode using RT2832U.

**Comment by andimik** [comment]
What about Qt-DAB itself? Same issue?

**Comment by miken101** [comment]
Qt-DAB Appimage has no issues, I'll try a compile from source later today and see if that works.

**Comment by marcogrecopriolo** [comment]
My goto build machine runs OpenSuse Leap 15.2
I'll do the next build on Ubuntu 20.04 LTS if that helps.
